# cluster-config.yml
kind: Cluster
name: sock-shop
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 80
    protocol: TCP
  - containerPort: 31090
    hostPort: 9090
    protocol: TCP
  - containerPort: 31300
    hostPort: 3000
    protocol: TCP
  - containerPort: 30010
    hostPort: 8080
    protocol: TCP
